### ISSUE TITLE
Use property instead of to_json(),to_yaml(),etc.

### ISSUE THREAD

**Issue by gaojiuli** [cdgriffith/Box#10]
Use
```
box.json
box.yaml
box.csv


@property
def json(self):
    return {}
```

but not 
```
box.to_json()
box.to_yaml()
box.to_csv()
```
which is more pythonic. And the arguments  "filename" of to_yaml() could be instead by a method "save()". What do you think?

**Comment by cdgriffith** [comment]
`box.json` is prettier and shorter, I agree, however I worry that a lot of people might have data with those values in them, which would error if your data is in such a box. 

For example, this would cause an error:

```python
import box, requests

req = box.Box(url='http://cdgriffith.com', method='POST', json={'value':1}, headers={'session': 'user1234'})
requests.request(**req) 
```


`to_csv` is also a good idea, I will have to look into adding that. Going to have to think if it should be list of lists format, aka would be a property of `BoxList`, or rather a dictionary of keys would be the column names and lists of the data in the column. (or heck, support both methods, depending on which it is invoked on).

**Comment by gaojiuli** [comment]
I solved the problem you figure out.

https://github.com/cdgriffith/Box/blob/master/box.py#L164-L178

```python
@property
def json(self):
    return json.dumps(self.to_dict())  
```

https://github.com/cdgriffith/Box/blob/master/box.py#L202-L208

```python
if not k == 'json':
    setattr(self, k, v)
```

I think you could understand want I mean.

**Comment by cdgriffith** [comment]
That's actually how it currently works, it protects any custom methods (and built-ins) from being overwritten. The issue is I think 'json' and 'yaml' are going to be popular keys, and I don't want to limit people from having them in their Box. Whereas it is a lot less likely for an incoming dictionary to have a 'to_yaml' or 'to_json' key. 

The second reason is that other libraries already have similarly named functions, so it makes it more common across tools. Such as `addict`'s [to_dict()](https://github.com/mewwts/addict#recursive-fallback-to-dict) and `Bunch`'s [to_yaml()](https://github.com/dsc/bunch/blob/master/bunch/__init__.py#L351).

So I am pretty set on keeping it as is for now. However it is always possible to subclass and have your own version that will act that way. 

```python

class MyBox(Box):

    def __init__(self, *args, **kwargs):
        self._protected_keys += ['json', 'yaml', 'csv']
        super(MyBox, self).__init__(*args, **kwargs)

    @property
    def json(self):
        return json.dumps(self.to_dict())

    ...
```

Also thanks for the `to_csv` idea, I opened it's own issue to track at https://github.com/cdgriffith/Box/issues/11

**Comment by cdgriffith** [comment]
I am having a change of heart and adding a `PropertyBox` as a tentative `3.x` feature. Not part of the default `Box`, because I still think there is going to be a lot of people trying to access `my_box.json` fields, but those who are aware they want the quick access can use the new class. 

https://github.com/cdgriffith/Box/commit/231abc5592e4877798e4b66c5e267e39fd11d028#diff-5694fec7e6d182e04c7d3fee3bbb4c40R679

**Comment by cdgriffith** [comment]
Added in 3.0 as SBox (aka shorthand box) https://github.com/cdgriffith/Box#sbox
