### ISSUE TITLE
Problem with references to subdicts in Box 4.0.x

### ISSUE THREAD

**Issue by richieadler** [cdgriffith/Box#126]
Given this program:

```python
#!/usr/bin/env python3

import box

info = box.Box({'initial': {1: 'uno', 2: 'dos'}}, default_box=True)
d = info.other = {}
d[3] = 'three'
d[4] = 'four'

print('Box version: ', box.__version__)
print(info.to_yaml())
```

With Box 4.0.4 I get this result:

```
Box version:  4.0.4
initial:
  1: uno
  2: dos
other: {}
```

Prior to Box 4.0.1 I got the correct result:

```
Box version:  3.4.6
initial:
  1: uno
  2: dos
other:
  3: three
  4: four
```

**Comment by cdgriffith** [comment]
This is actually working as intended in the new version, but seems odd because of how Python handles "chained assignment" (when it's actually more of a ["right most assignment"](https://stackoverflow.com/a/36346517/3244542))

In Box 4, there is no more lazy conversion of dictionaries on retrieval instead of on insert. Which means the object is being converted on creation, so the empty `{}` you are setting to both `d` and `info.other` is converted to a new Box object for the `info.other` only and the original is being forgotten about. 

So why did this change? Take your example, but this time, lets add something else after printing once. 

```
import box

info = box.Box({'initial': {1: 'uno', 2: 'dos'}})
info.other = d = {}
d[3] = 'three'
d[4] = 'four'

print('Box version: ', box.__version__)
# 3.4.6
print(info)
# {'initial': {1: 'uno', 2: 'dos'}, 'other': {3: 'three', 4: 'four'}}

d[5] = 'five'

print(info)
# {'initial': {1: 'uno', 2: 'dos'}, 'other': {3: 'three', 4: 'four'}}
# Wait, no five? 
```

This is where it matters and why this needed to change. Box 3 would still be using the referenced object until it was retrieved once (via any `__getitem__` or `__getattr__` call, including stuff like print). Notice that 5 was set properly in the `d` dictionary, but the `info.other` was transferred into a new Box object with new reference after the print.

**Comment by richieadler** [comment]
So I'm guessing that to get the desired result I would have to reassign the reference to the original value.
Many scripts to check now...
