### ISSUE TITLE
[5.0.0] Spurious values appear in default Box "repr"

### ISSUE THREAD

**Issue by richieadler** [cdgriffith/Box#155]
```python
>>> b = box.Box(default_box=True)
>>> b
<Box: {}>
>>> b.first = ''
>>> b
<Box: {'_obj_': {}, '_oleobj_': {'GetTypeInfoCount': {}}, 'first': ''}>
>>> dict(b)
{'_obj_': <Box: {}>, '_oleobj_': <Box: {'GetTypeInfoCount': {}}>, 'first': ''}
```

**Comment by cdgriffith** [comment]
Thanks for the fast report! 

This is due to some interpreters doing checks for methods existing, and being saved. I am adding a fix that will at least exclude them being saved as long as they start and end with underscores, as most should be restricted properties or magic methods I hope. 

Being fixed now in 5.0.1
