### ISSUE TITLE
Support for tracking the box "namespace"

### ISSUE THREAD

**Issue by JacobHayes** [cdgriffith/Box#226]
I have some nested Boxes using an overridden `__convert_and_store` in a subclass to convert values to an expected type (eg: I want all values to be an `int` or some other custom class). For that conversion, I would like to know the "namespace" of the Box/value in order to reference it in the conversion and  show nicer error messages.

For example, when handling the conversion of `5` in the example below:
```python
box = MyBox({"a": {"b": {"c": 5}}})
```
I would like to know that I'm assigning to `("a", "b", "c")`.

This is quite hard to setup only in a subclass because of the recursive value conversion (and copying) during `__init__` and conversion doesn't give a good hook to intercept _after_ the box is created, but _before_ sub-boxes are created.

I think the easiest way to support this is by adding a `box_path` or `box_namespace` param to `__init__` (defaulting to `()`) and then into `_box_config`, which can be passed through (and extended) in `__get_default` and `__convert_and_store` when creating sub-boxes.

Is this something you'd be open to? I'd be happy to make a PR for this if so!

**Comment by ipcoder** [comment]
Actually, I have a similar problem, though formulated it differently.
May be this angle could be useful for you as well.

I use Box heavily with `box_dots`, and used to think about keys as paths, so I have  sub-classed 
Box (to `TBox`) to make this default option, and to add several enhancing work in this mode.

First, I re-implemented `__setitem__` to allow:

```python
b = Box()
b['z.y.z'] = "Hi" 
# b == {'x': {'y': {'z': 1}}}
```
Such initializations are possible:
```python
b = TBox({
    'x.y.z': 1,
    'x.y.w': 2,
    'x.m': 100,
    'x.n': {'k.p':200}
})
```

In general, I believe working with dots should be symmetrical for reading and writing.
Now `a = b["x.y"'] ` reads `b.x.y` item, but `b["x.y"] = a` writes to a '"x.y"' key of `b`.

Implementation is rather straightforward and does not seem to conflict with the rest of Box functionality:

```python
class TBox(Box):

   ...

   def __getitem__(self, item, _ignore_default=False):
        """
        Adds support to deep dot separated keys.
        :param item: top level or dot separated
        :return:
        """
        if '.' in item:
            key, rest = item.split('.', 1)
            v = super().__getitem__(key, _ignore_default)
            if isinstance(v, Box):
                return v[rest]
            return v
        else:
            return super().__getitem__(item, _ignore_default)
```

I am also missing `b.x.y.z = a`  which does not work without `default_box=True` , which itself is not really useful, due to issues like #236 (also here comment https://github.com/cdgriffith/Box/issues/164#issuecomment-1359179014).

But before some solution for the default_box problem is found, `b['x.y.z'] = a` does a trick as the difference is mainly syntactic.

**Comment by nishikantparmariam** [comment]
> I think the easiest way to support this is by adding a box_path or box_namespace param

+1 for this feature.

**Comment by JacobHayes** [comment]
I revived #227 as #240 for the `box_namespace` config.

**Comment by cdgriffith** [comment]
Adding this feature in Box 7! Please test and give feedback if possible `pip install python-box[all]~=7.0.0rc0`  (Thanks again @JacobHayes for the PR! )

**Comment by JacobHayes** [comment]
7.0.0rc0 [worked for me](https://github.com/artigraph/artigraph/pull/306/commits/33b1601cf04f75a1e87b2567fb2e38c19602aae8) (replacing my workarounds, which fixed a couple bugs)!

**Comment by cdgriffith** [comment]
Added in [7.0.0](https://github.com/cdgriffith/Box/releases/tag/7.0.0)
